name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      ['main']
    types: [opened]

jobs: 
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Instructions on the PR
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: godkelvin/comment-on-pr-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}