name: Continuous Integration

on:
  pull_request:
    branches:
      ['main']
    types: [opened]

jobs: 
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Instructions on the PR
        uses: actions/github-script@v7
        with:
          script: |
            const author = context.payload.pull_request.user.login;
            const commentBody = `Olá, @${author}! 👋

            Obrigado por abrir este PR.

            Por favor, verifique se:
            - [ ] Todos os testes estão passando
            - [ ] O PR está vinculado a uma issue (se aplicável)
            - [ ] Você preencheu a descrição do PR com detalhes claros

            Nos avise se precisar de ajuda! 🚀`;

            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });